### ISSUE TITLE
Firefix is Error

### ISSUE THREAD

**Issue by kencery** [chao/RESTClient#229] opened 2016-05-12 10:29 UTC
Hi,
    I USE Firefix plug-in Is Error，Error message as shown,Why is that? please handle!!!

![image](https://cloud.githubusercontent.com/assets/7973271/15211676/2bd5cc72-186f-11e6-8c1f-33616f3c98f3.png)

**Comment by saerdnaer** [comment] 2016-05-12 10:46
Duplicate of https://github.com/chao/RESTClient/issues/229

**Comment by kencery** [comment] 2016-05-12 10:53
I don't see is how to solve?How to solve?Before use is good, now have a problem~

**Comment by saerdnaer** [comment] 2016-05-12 11:01
You can downgrade to Firefox 45
* https://github.com/chao/RESTClient/issues/220#issuecomment-216058456
* https://github.com/chao/RESTClient/issues/220#issuecomment-216249317
Wait till a new version of the addon is released
* https://github.com/chao/RESTClient/issues/220#issuecomment-216922755
or apply the patch manually – if you know how to modify an firefox addon
* https://github.com/chao/RESTClient/commit/cd1425479c84c7c4898ab76486a31bfb578dd1d7

**Comment by kencery** [comment] 2016-05-12 11:10
Thank you very much, I know

**Closed** 2016-05-12 15:59 UTC
