### ISSUE TITLE
Header Not Responding

### ISSUE THREAD

**Issue by prashobh-k** [chao/RESTClient#223] opened 2016-05-06 04:29 UTC
While filling all the header fields (Content-type & application/json) and after that press ok,its not responding, because of that i am unable to set mime type .

**Comment by nitiniq** [comment] 2016-05-07 09:07
same issue i am also not able to set header.
It was working fine but now it is not responding.

**Comment by eugenp** [comment] 2016-05-08 21:45
I'm seeing the same thing - I'm not longer able to add headers to requests. 
Any idea what's going on?
Cheers, 
Eugen.

**Comment by prashobh-k** [comment] 2016-05-09 06:42
it is still not working because of the error i changed to another app
(Rested) which works fine..

**Comment by Tshuuls** [comment] 2016-05-12 07:45
I have the same problem. It worked fine yesterday and now pressing on the OK after entering the authetication or headers does not do anything

**Comment by saerdnaer** [comment] 2016-05-12 10:48
Probably duplicate of #229. Does it work, when you revert to Firefox 45?

**Comment by benel** [comment] 2016-05-18 21:58
Please check #220 for the manual installation of the fix and for the current status of the official update.

**Closed by benel** 2016-05-18 21:58 UTC

**Comment by prashobh-k** [comment] 2016-11-06 10:29
Hey chao/RESTClient,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Prashobh

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=X5ctQTm5&invitationId=6200976823250149376&trk=eml-invite_guest-invite_guest-203-india_a&trkEmail=eml-invite_guest-invite_guest-203-india_a-null-0%7Eiv6hxoda%7Edk



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iv6hxoda-dk&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFuuA1_070aGQAAAVg5LxJbhjZNutkTGcwQFqD3GoNdW17qDkh17AJNGOFVr1OQqwYt7NW54mZ21nOMJgxIa0xdP4e6MH27R2ThwTweFF0xmz3lnOcgxxRGOVhbpnfYDpEi8ppdWiLxSy-Mn3Br9RmIbH3kSlXKJ1ucnDHOeIO-EemaTaCgFT6q8uxuENVqZ4wi&eid=0-iv6hxoda-dk


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iv6hxoda-dk&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by prashobh-k** [comment] 2016-11-10 11:20
Prashobh k.v would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=X5ctQTm5&invitationId=6200976823250149376&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-9f53zw%7Eivbwwxnj%7Eq8

View Prashobh k.v&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=X5ctQTm5&invitationId=6200976823250149376&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-9f53zw%7Eivbwwxnj%7Eq8





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=9f53zw-ivbwwxnj-q8&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=9f53zw-ivbwwxnj-q8&loid=AQFnqfUAzc84VwAAAVhN98jAP_9F9X3fb0bcY0X8roQl3TWIdQc6pemTPOSyGc-D2VaB_SJm7AqlYwu2K-0bb5WQAvHPseM6ptYbdARWCtHyJObV676fyuUjgZcGd4A2DpvCSyvTzgvg7NfDh3Yg-fOyVuiIrP1yjsCcDK-f6C3puE4tfY0iAXt-CB0bH5g3LdC4

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=9f53zw-ivbwwxnj-q8&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by prashobh-k** [comment] 2016-11-17 09:11
Hi ,

Prashobh k.v would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=X5ctQTm5&invitationId=6200976823250149376&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-9f53zw%7Eivlx178g%7Epm

View Prashobh k.v&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=X5ctQTm5&invitationId=6200976823250149376&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-9f53zw%7Eivlx178g%7Epm





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=9f53zw-ivlx178g-pm&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=9f53zw-ivlx178g-pm&loid=AQFLhnPKYXwtyAAAAVhxjbaL2HzJ2AzT9gagkM7609JYm3-nw-OTjgA2jKKl90gTw0NaolJfH_QqbarONLTWTpRLqz0Hw2BIVjFBrNtS4j4IFvWxXpAWPq-UXbn_dow8UlU6G3ue98c8u1yyulNyyHOAtNxwMZmZtzeWooMobRKBZ0i8z5Nrgztjyc9YaGNOIyxz

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=9f53zw-ivlx178g-pm&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
