### ISSUE TITLE
Show curl code

### ISSUE THREAD

**Issue by MatheMatrix** [chao/RESTClient#181] opened 2014-10-21 05:55 UTC
RESTClient is a nice tool, but sometimes I need to show curl code to others, do we have any support?

**Comment by rjmvalk3** [comment] 2015-04-10 11:32
+1

**Comment by andredasilvapinto** [comment] 2015-07-23 11:41
+1

**Comment by andredasilvapinto** [comment] 2015-07-23 11:42
seems to be a duplicate of https://github.com/chao/RESTClient/issues/110

**Comment by RockyMM** [comment] 2017-10-11 07:44
+1

**Comment by chao** [comment] 2018-01-11 09:07
Curl is supported in 3.0.5, please update to the latest version.

**Closed by chao** 2018-01-11 09:07 UTC
