### ISSUE TITLE
RESTClient Not Adding Authentication 

### ISSUE THREAD

**Issue by tewest** [chao/RESTClient#233] opened 2016-05-18 16:45 UTC
I have an issue, the REST client is not working properly for basic authentication it doesn't do anything when I add in a username and password and then click "ok"

As well the GET/PUT requests I have saved do not do anything when I click "send"

I have tried re-installing into firefox with no luck.

**Comment by benel** [comment] 2016-05-18 21:54
Duplicate of #220.

**Closed by benel** 2016-05-18 21:54 UTC
